# Generated by Django 4.0.6 on 2022-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='project_images'),
        ),
    ]
