# Generated by Django 4.0.6 on 2022-07-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_skill_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
    ]
